[package]
name = "keyrock_challenge_proto"
version = "1.0.0"
authors = ["Finn Fiedler"]
edition = "2021"

[dependencies]
prost = "0.11.0"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.0"


[build-dependencies]
tonic-build = "0.8"